# Generated by Django 4.0.3 on 2022-03-17 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_name', models.CharField(max_length=150, verbose_name='picup name')),
                ('pickup_address', models.CharField(max_length=250, verbose_name='picup address')),
                ('pickup_phone_number', models.CharField(max_length=50, verbose_name='pickup phone number')),
                ('pickup_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='pickup area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
