# Generated by Django 4.0.5 on 2022-07-07 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('RIDER', 'Rider'), ('MERCHANT', 'Merchant')], db_index=True, default='MERCHANT', max_length=50, verbose_name='Type')),
                ('username', models.CharField(blank=True, db_index=True, max_length=155, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +8801555555550, Up to 11 digits allowed.', regex='^(((?:\\+88)?(?:\\d{11}))|((?:01)?(?:\\d{11})))$')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_index=True, max_length=6, verbose_name='gender')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('otp', models.CharField(blank=True, max_length=6, verbose_name='otp')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
