# Generated by Django 4.0.5 on 2022-07-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_managements', '0001_initial'),
        ('accounts', '0003_alter_account_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_managements.branch'),
        ),
    ]
