# Generated by Django 4.0.3 on 2022-03-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('percels', '0005_alter_percel_status'),
        ('accounts', '0002_account_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bar_code', models.ImageField(upload_to='delivery-barcode/')),
                ('completed', models.BooleanField(default=False)),
                ('delivery_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_by', to='accounts.rider', verbose_name='delivery by')),
                ('delivery_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_to', to='accounts.manager')),
                ('percel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='percel_delivey', to='percels.percel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
