# Generated by Django 4.0.3 on 2022-03-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_admin'),
        ('perceldelivery', '0002_remove_perceldelivery_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perceldelivery',
            name='bar_code',
        ),
        migrations.AlterField(
            model_name='perceldelivery',
            name='delivery_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_by', to='accounts.rider', verbose_name='delivery by'),
        ),
        migrations.AlterField(
            model_name='perceldelivery',
            name='delivery_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_to', to='accounts.manager'),
        ),
    ]
