# Generated by Django 4.0.5 on 2022-07-04 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_account_branch'),
        ('delivery_managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Pending', 'Pending'), ('PC', 'Pickup Complete')], db_index=True, default='Pending', max_length=9)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_pickup', to='delivery_managements.parcel')),
                ('pickup_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_by', to='accounts.rider')),
                ('pickup_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Pickup',
                'verbose_name_plural': 'Parcel Pickup',
            },
        ),
        migrations.CreateModel(
            name='ParcelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], db_index=True, default='Pending', max_length=9)),
                ('delivery_rider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_rider', to='accounts.rider')),
                ('delivery_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_to', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_delivery', to='delivery_managements.parcel')),
            ],
            options={
                'verbose_name': 'Parcel Delivery',
                'verbose_name_plural': 'Parcel Deliveries',
            },
        ),
    ]
