# Generated by Django 4.0.5 on 2022-07-07 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_managements', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelpickup',
            name='pickup_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_by', to='accounts.rider'),
        ),
        migrations.AddField(
            model_name='parcelpickup',
            name='pickup_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='delivery_rider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_rider', to='accounts.rider'),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='delivery_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='parcel',
            field=models.ManyToManyField(related_name='parcel_delivery', to='delivery_managements.parcel'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_managements.branch', verbose_name='delivery location'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_managements.pickuplocation'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='delivery_managements.location'),
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_managements.location'),
        ),
        migrations.AddField(
            model_name='branch',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='my_branch', to=settings.AUTH_USER_MODEL),
        ),
    ]
