# Generated by Django 4.0.5 on 2022-07-04 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_managements', '0002_parcelpickup_parceldelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck_diver_name', models.CharField(max_length=50)),
                ('truck_diver_phone_number', models.CharField(db_index=True, max_length=15)),
                ('truck_plate_number', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Pending', 'Pending'), ('SC', 'Shipment Completed'), ('Return', 'Return')], db_index=True, default='Pending', max_length=10)),
                ('parcel', models.ManyToManyField(to='delivery_managements.parcel')),
                ('receiver_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_receiver_branch', to='delivery_managements.branch')),
                ('sender_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_sender_branch', to='delivery_managements.branch')),
                ('shipment_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
