# Generated by Django 4.0.5 on 2022-07-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_managements', '0003_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='traking_id',
            new_name='tracking_id',
        ),
    ]
