# Generated by Django 4.0.5 on 2022-07-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_managements', '0004_rename_traking_id_parcel_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceldelivery',
            name='parcel',
        ),
        migrations.AddField(
            model_name='parceldelivery',
            name='parcel',
            field=models.ManyToManyField(related_name='parcel_delivery', to='delivery_managements.parcel'),
        ),
        migrations.RemoveField(
            model_name='parcelpickup',
            name='parcel',
        ),
        migrations.AddField(
            model_name='parcelpickup',
            name='parcel',
            field=models.ManyToManyField(related_name='parcel_pickup', to='delivery_managements.parcel'),
        ),
    ]
