# Generated by Django 4.0.3 on 2022-03-17 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Percel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traking_id', models.CharField(max_length=10, verbose_name='traking id')),
                ('customer_name', models.CharField(max_length=100, verbose_name='customer name')),
                ('customer_phone_number', models.CharField(max_length=100, verbose_name='customer phone number')),
                ('customer_address', models.CharField(max_length=250, verbose_name='customer address')),
                ('parcel_weight', models.CharField(default='500gm', max_length=10, verbose_name='percel weight')),
                ('product_selling_price', models.CharField(max_length=15, verbose_name='product selling price')),
                ('product_category', models.CharField(max_length=100, verbose_name='product category')),
                ('description', models.TextField(max_length=350, verbose_name='description')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Processing', 'Processing'), ('Cancel', 'Cancel'), ('Return', 'Return'), ('Completed', 'Completed')], max_length=15, verbose_name='status')),
                ('delivery_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percel_delivery', to='accounts.rider', verbose_name='delivery by')),
                ('delivery_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='delivery location')),
                ('pickup_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percel_pickup', to='accounts.rider', verbose_name='pickup by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percel', to=settings.AUTH_USER_MODEL, verbose_name='percel')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
