# Generated by Django 4.0.3 on 2022-03-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickuplocations', '0001_initial'),
        ('percels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='percel',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pickuplocations.pickuplocation'),
        ),
        migrations.AlterField(
            model_name='percel',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('PickupPending', 'PickupPending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancel', 'Cancel'), ('Return', 'Return')], default='PickupPending', max_length=15, verbose_name='status'),
        ),
    ]
