# Generated by Django 4.0.3 on 2022-03-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('percels', '0003_alter_percel_traking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percel',
            name='delivery_by',
        ),
        migrations.RemoveField(
            model_name='percel',
            name='pickup_by',
        ),
    ]
