# Generated by Django 4.0.3 on 2022-03-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percels', '0004_remove_percel_delivery_by_remove_percel_pickup_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percel',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('PickupPending', 'PickupPending'), ('DeliveryPending', 'DeliveryPending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancel', 'Cancel'), ('Return', 'Return')], default='PickupPending', max_length=15, verbose_name='status'),
        ),
    ]
