# Generated by Django 4.0.3 on 2022-03-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percelpickup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percelpickup',
            name='completed',
        ),
        migrations.AddField(
            model_name='percelpickup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Completed', 'Completed'), ('Cance', 'Cance')], default='Pending', max_length=10),
        ),
    ]
