# Generated by Django 4.0.3 on 2022-03-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_admin'),
        ('percelpickup', '0002_remove_percelpickup_completed_percelpickup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percelpickup',
            name='pickup_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_by', to='accounts.rider'),
        ),
        migrations.AlterField(
            model_name='percelpickup',
            name='pickuped_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickuped_to', to='accounts.manager'),
        ),
    ]
